# Generated by Django 3.2.9 on 2021-11-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripcion',
            new_name='descripciones',
        ),
    ]
